version: "3"
services:
  db:
    image: "mongo:latest"
    container_name: db_apbp
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: apbp
      MONGO_INITDB_ROOT_PASSWORD: tempApbp.51
    volumes:
      - ./apbpdata:/data/db
    networks:
      - apbp-network
    ports:
      - "27017:27017"
    expose:
      - "27017"
  app:
    build: .
    ports:
      - "80:8000"
    volumes:
      - .:/app
    env_file:
      - .env.docker
    networks:
      - apbp-network
    depends_on:
      - db

networks:
  apbp-network:
    driver: bridge
volumes:
  apbpdata:
